# Generated by Django 4.2.1 on 2023-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pw_confirm',
            field=models.CharField(default='', max_length=30, verbose_name='유저 비밀번호 확인'),
            preserve_default=False,
        ),
    ]
